name: Deployment pipeline

on:
  push:
    branches:
      - main
  pull_request:
    branches: [main]
    types: [opened, synchronize]

jobs:
  build_and_test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v6
      - uses: actions/setup-node@v6
        with: 
          node-version: '24'
      - name: Install dependencies
        run: npm run install:all
      - name: Lint backend
        run: npm run lint --prefix server
      - name: Lint frontend
        run: npm run lint --prefix client
      - name: Test backend
        run: npm run test --prefix server
        env:
          TEST_MONGODB_URI: ${{ secrets.TEST_MONGODB_URI }}
          SECRET: ${{ secrets.SECRET }}
      - name: Test frontend
        run: npm run test --prefix client
      - name: Build 
        run: npm run build --prefix client
      - name: Install playwright dependencies
        run: npx playwright install --with-deps
      - name: Run Playwright tests
        run: npm run test:e2e
        env:
          MONGODB_URI: ${{ secrets.MONGODB_URI }}
          SECRET: ${{ secrets.SECRET }}
          PORT: 3003
  
  deploy:
    needs: [build_and_test]
    runs-on: ubuntu-latest
    if: ${{ github.event_name == 'push' && !contains(join(github.event.commits.*.message, ' '), '#skip') }}
    steps:
      - uses: actions/checkout@v4
      - uses: superfly/flyctl-actions/setup-flyctl@master
      - run: flyctl deploy --remote-only
        env:
          FLY_API_TOKEN: ${{ secrets.FLY_API_TOKEN }}

  tag_release:
    needs: [deploy]
    runs-on: ubuntu-latest
    if: ${{ github.event_name == 'push' && !contains(join(github.event.commits.*.message, ' '), '#skip') }}
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: '0'
      
      - name: Bump version and push tag
        uses: anothrNick/github-tag-action@1.75.0
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          DEFAULT_BUMP: 'patch'

  notify_success:
    needs: [deploy]
    runs-on: ubuntu-latest
    if: ${{ success() && github.event_name == 'push' && !contains(join(github.event.commits.*.message, ' '), '#skip') }}
    steps:
      - uses: actions/checkout@v4
      - uses: sarisia/actions-status-discord@v1
        with:
          webhook: ${{ secrets.DISCORD_WEBHOOK }}
          title: "✅ **Deployment Successful!** A new version deployed to production"
          color: 0x008000
  
  notify_failure:
    needs: [build_and_test, deploy, tag_release]
    runs-on: ubuntu-latest
    if: ${{ failure() }}
    steps:
      - uses: actions/checkout@v4
      - uses: sarisia/actions-status-discord@v1
        with:
          webhook: ${{ secrets.DISCORD_WEBHOOK }}
          title: "❌ **Build Failed!** The pipeline encountered an error"
          color: 0xff0000
